-- ============================================================
-- V20: Ozon FBO orders - полный технический слой вместо укороченных staging
-- ============================================================

CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS staging.ozon_fbo_order_items_full (
    posting_number  TEXT        NOT NULL,
    line_number     INT         NOT NULL,
    order_id        BIGINT,
    order_number    TEXT,
    status          TEXT,
    substatus       TEXT,
    created_at      TIMESTAMPTZ,
    in_process_at   TIMESTAMPTZ,
    shipment_date   TIMESTAMPTZ,
    cancel_reason_id BIGINT,
    cancel_reason   TEXT,
    cancellation_initiator TEXT,
    cancellation_type TEXT,
    analytics_city  TEXT,
    analytics_delivery_type TEXT,
    analytics_is_legal BOOLEAN,
    analytics_is_premium BOOLEAN,
    analytics_payment_type_group_name TEXT,
    analytics_warehouse_id BIGINT,
    analytics_warehouse_name TEXT,
    analytics_client_delivery_date_begin TIMESTAMPTZ,
    analytics_client_delivery_date_end TIMESTAMPTZ,
    financial_cluster_from TEXT,
    financial_cluster_to TEXT,
    legal_company_name TEXT,
    legal_inn TEXT,
    legal_kpp TEXT,
    external_order_is_external BOOLEAN,
    external_order_platform_name TEXT,
    products_count INT NOT NULL DEFAULT 0,
    financial_products_count INT NOT NULL DEFAULT 0,
    additional_data_count INT NOT NULL DEFAULT 0,
    additional_data JSONB NOT NULL DEFAULT '[]'::jsonb,
    product_is_marketplace_buyout BOOLEAN NOT NULL DEFAULT FALSE,
    product_offer_id TEXT NOT NULL DEFAULT '',
    product_name TEXT,
    product_sku BIGINT,
    product_quantity INT NOT NULL DEFAULT 0,
    product_price_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    product_price_currency TEXT,
    product_digital_codes_count INT NOT NULL DEFAULT 0,
    product_digital_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    financial_product_id BIGINT,
    financial_payout NUMERIC(14,2) NOT NULL DEFAULT 0,
    financial_old_price NUMERIC(14,2) NOT NULL DEFAULT 0,
    financial_price NUMERIC(14,2) NOT NULL DEFAULT 0,
    financial_total_discount_value NUMERIC(14,2) NOT NULL DEFAULT 0,
    financial_total_discount_percent NUMERIC(8,2) NOT NULL DEFAULT 0,
    financial_actions_count INT NOT NULL DEFAULT 0,
    financial_actions JSONB NOT NULL DEFAULT '[]'::jsonb,
    financial_commission_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    financial_commission_percent NUMERIC(8,2) NOT NULL DEFAULT 0,
    financial_commission_currency TEXT,
    posting_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    product_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    financial_product_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_run_id TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (posting_number, line_number)
);

CREATE INDEX IF NOT EXISTS idx_ozon_fbo_order_items_full_in_process
    ON staging.ozon_fbo_order_items_full (in_process_at DESC);
CREATE INDEX IF NOT EXISTS idx_ozon_fbo_order_items_full_offer
    ON staging.ozon_fbo_order_items_full (product_offer_id);
CREATE INDEX IF NOT EXISTS idx_ozon_fbo_order_items_full_sku
    ON staging.ozon_fbo_order_items_full (product_sku);
CREATE INDEX IF NOT EXISTS idx_ozon_fbo_order_items_full_status
    ON staging.ozon_fbo_order_items_full (status);

INSERT INTO staging.ozon_fbo_order_items_full (
    posting_number, line_number, order_id, order_number, status, substatus,
    created_at, in_process_at, shipment_date,
    cancel_reason_id, cancel_reason, cancellation_initiator, cancellation_type,
    analytics_city, analytics_delivery_type, analytics_is_legal, analytics_is_premium,
    analytics_payment_type_group_name, analytics_warehouse_id, analytics_warehouse_name,
    analytics_client_delivery_date_begin, analytics_client_delivery_date_end,
    financial_cluster_from, financial_cluster_to,
    legal_company_name, legal_inn, legal_kpp,
    external_order_is_external, external_order_platform_name,
    products_count, financial_products_count, additional_data_count, additional_data,
    product_is_marketplace_buyout, product_offer_id, product_name, product_sku,
    product_quantity, product_price_amount, product_price_currency,
    product_digital_codes_count, product_digital_codes,
    financial_product_id, financial_payout, financial_old_price, financial_price,
    financial_total_discount_value, financial_total_discount_percent,
    financial_actions_count, financial_actions,
    financial_commission_amount, financial_commission_percent, financial_commission_currency,
    posting_payload, product_payload, financial_product_payload, source_run_id
)
SELECT
    r.posting_number,
    p.ordinality::int AS line_number,
    r.order_id,
    r.payload->>'order_number',
    r.status,
    r.payload->>'substatus',
    NULLIF(r.payload->>'created_at', '')::timestamptz,
    r.in_process_at,
    r.shipment_date,
    NULLIF(r.payload->>'cancel_reason_id', '')::bigint,
    r.payload#>>'{cancellation,cancel_reason}',
    r.payload#>>'{cancellation,cancellation_initiator}',
    r.payload#>>'{cancellation,cancellation_type}',
    r.payload#>>'{analytics_data,city}',
    r.payload#>>'{analytics_data,delivery_type}',
    COALESCE((r.payload#>>'{analytics_data,is_legal}')::boolean, FALSE),
    COALESCE((r.payload#>>'{analytics_data,is_premium}')::boolean, FALSE),
    r.payload#>>'{analytics_data,payment_type_group_name}',
    NULLIF(r.payload#>>'{analytics_data,warehouse_id}', '')::bigint,
    r.payload#>>'{analytics_data,warehouse_name}',
    NULLIF(r.payload#>>'{analytics_data,client_delivery_date_begin}', '')::timestamptz,
    NULLIF(r.payload#>>'{analytics_data,client_delivery_date_end}', '')::timestamptz,
    r.payload#>>'{financial_data,cluster_from}',
    r.payload#>>'{financial_data,cluster_to}',
    r.payload#>>'{legal_info,company_name}',
    r.payload#>>'{legal_info,inn}',
    r.payload#>>'{legal_info,kpp}',
    COALESCE((r.payload#>>'{external_order,is_external}')::boolean, FALSE),
    r.payload#>>'{external_order,platform_name}',
    CASE WHEN jsonb_typeof(r.payload->'products') = 'array' THEN jsonb_array_length(r.payload->'products') ELSE 0 END,
    CASE WHEN jsonb_typeof(r.payload#>'{financial_data,products}') = 'array' THEN jsonb_array_length(r.payload#>'{financial_data,products}') ELSE 0 END,
    CASE WHEN jsonb_typeof(r.payload->'additional_data') = 'array' THEN jsonb_array_length(r.payload->'additional_data') ELSE 0 END,
    COALESCE(r.payload->'additional_data', '[]'::jsonb),
    COALESCE((p.product->>'is_marketplace_buyout')::boolean, FALSE),
    COALESCE(p.product->>'offer_id', ''),
    p.product->>'name',
    NULLIF(p.product->>'sku', '')::bigint,
    COALESCE(NULLIF(p.product->>'quantity', '')::int, 0),
    COALESCE(NULLIF(p.product#>>'{price,amount}', '')::numeric, 0),
    p.product#>>'{price,currency}',
    CASE WHEN jsonb_typeof(p.product->'digital_codes') = 'array' THEN jsonb_array_length(p.product->'digital_codes') ELSE 0 END,
    COALESCE(p.product->'digital_codes', '[]'::jsonb),
    NULLIF(f.financial_product->>'product_id', '')::bigint,
    COALESCE(NULLIF(f.financial_product->>'payout', '')::numeric, 0),
    COALESCE(NULLIF(f.financial_product->>'old_price', '')::numeric, 0),
    COALESCE(NULLIF(f.financial_product->>'price', '')::numeric, 0),
    COALESCE(NULLIF(f.financial_product->>'total_discount_value', '')::numeric, 0),
    COALESCE(NULLIF(f.financial_product->>'total_discount_percent', '')::numeric, 0),
    CASE WHEN jsonb_typeof(f.financial_product->'actions') = 'array' THEN jsonb_array_length(f.financial_product->'actions') ELSE 0 END,
    COALESCE(f.financial_product->'actions', '[]'::jsonb),
    COALESCE(NULLIF(f.financial_product#>>'{commission,amount}', '')::numeric, 0),
    COALESCE(NULLIF(f.financial_product#>>'{commission,percent}', '')::numeric, 0),
    f.financial_product#>>'{commission,currency}',
    r.payload,
    p.product,
    COALESCE(f.financial_product, '{}'::jsonb),
    r.source_run_id
FROM raw.ozon_fbo_postings r
CROSS JOIN LATERAL jsonb_array_elements(COALESCE(r.payload->'products', '[]'::jsonb))
    WITH ORDINALITY AS p(product, ordinality)
LEFT JOIN LATERAL (
    SELECT fp.value AS financial_product
    FROM jsonb_array_elements(COALESCE(r.payload#>'{financial_data,products}', '[]'::jsonb))
        WITH ORDINALITY AS fp(value, ordinality)
    WHERE fp.ordinality = p.ordinality
) f ON TRUE
ON CONFLICT (posting_number, line_number) DO UPDATE SET
    order_id = EXCLUDED.order_id,
    order_number = EXCLUDED.order_number,
    status = EXCLUDED.status,
    substatus = EXCLUDED.substatus,
    created_at = EXCLUDED.created_at,
    in_process_at = EXCLUDED.in_process_at,
    shipment_date = EXCLUDED.shipment_date,
    cancel_reason_id = EXCLUDED.cancel_reason_id,
    cancel_reason = EXCLUDED.cancel_reason,
    cancellation_initiator = EXCLUDED.cancellation_initiator,
    cancellation_type = EXCLUDED.cancellation_type,
    analytics_city = EXCLUDED.analytics_city,
    analytics_delivery_type = EXCLUDED.analytics_delivery_type,
    analytics_is_legal = EXCLUDED.analytics_is_legal,
    analytics_is_premium = EXCLUDED.analytics_is_premium,
    analytics_payment_type_group_name = EXCLUDED.analytics_payment_type_group_name,
    analytics_warehouse_id = EXCLUDED.analytics_warehouse_id,
    analytics_warehouse_name = EXCLUDED.analytics_warehouse_name,
    analytics_client_delivery_date_begin = EXCLUDED.analytics_client_delivery_date_begin,
    analytics_client_delivery_date_end = EXCLUDED.analytics_client_delivery_date_end,
    financial_cluster_from = EXCLUDED.financial_cluster_from,
    financial_cluster_to = EXCLUDED.financial_cluster_to,
    legal_company_name = EXCLUDED.legal_company_name,
    legal_inn = EXCLUDED.legal_inn,
    legal_kpp = EXCLUDED.legal_kpp,
    external_order_is_external = EXCLUDED.external_order_is_external,
    external_order_platform_name = EXCLUDED.external_order_platform_name,
    products_count = EXCLUDED.products_count,
    financial_products_count = EXCLUDED.financial_products_count,
    additional_data_count = EXCLUDED.additional_data_count,
    additional_data = EXCLUDED.additional_data,
    product_is_marketplace_buyout = EXCLUDED.product_is_marketplace_buyout,
    product_offer_id = EXCLUDED.product_offer_id,
    product_name = EXCLUDED.product_name,
    product_sku = EXCLUDED.product_sku,
    product_quantity = EXCLUDED.product_quantity,
    product_price_amount = EXCLUDED.product_price_amount,
    product_price_currency = EXCLUDED.product_price_currency,
    product_digital_codes_count = EXCLUDED.product_digital_codes_count,
    product_digital_codes = EXCLUDED.product_digital_codes,
    financial_product_id = EXCLUDED.financial_product_id,
    financial_payout = EXCLUDED.financial_payout,
    financial_old_price = EXCLUDED.financial_old_price,
    financial_price = EXCLUDED.financial_price,
    financial_total_discount_value = EXCLUDED.financial_total_discount_value,
    financial_total_discount_percent = EXCLUDED.financial_total_discount_percent,
    financial_actions_count = EXCLUDED.financial_actions_count,
    financial_actions = EXCLUDED.financial_actions,
    financial_commission_amount = EXCLUDED.financial_commission_amount,
    financial_commission_percent = EXCLUDED.financial_commission_percent,
    financial_commission_currency = EXCLUDED.financial_commission_currency,
    posting_payload = EXCLUDED.posting_payload,
    product_payload = EXCLUDED.product_payload,
    financial_product_payload = EXCLUDED.financial_product_payload,
    source_run_id = EXCLUDED.source_run_id,
    updated_at = NOW();

DROP VIEW IF EXISTS analytics.ozon_fbo_order_items_flat;

CREATE OR REPLACE VIEW analytics.ozon_fbo_order_items_flat AS
SELECT
    posting_number,
    line_number,
    order_id,
    order_number,
    status,
    substatus,
    created_at,
    in_process_at,
    shipment_date,
    cancel_reason_id,
    cancel_reason,
    cancellation_initiator,
    cancellation_type,
    analytics_city,
    analytics_delivery_type,
    analytics_is_legal,
    analytics_is_premium,
    analytics_payment_type_group_name,
    analytics_warehouse_id,
    analytics_warehouse_name,
    analytics_client_delivery_date_begin,
    analytics_client_delivery_date_end,
    financial_cluster_from,
    financial_cluster_to,
    legal_company_name,
    legal_inn,
    legal_kpp,
    external_order_is_external,
    external_order_platform_name,
    products_count,
    financial_products_count,
    additional_data_count,
    product_sku AS sku,
    product_offer_id AS offer_id,
    product_name AS name,
    product_quantity AS quantity,
    product_price_amount AS price,
    product_price_currency AS currency_code,
    product_is_marketplace_buyout AS is_marketplace_buyout,
    product_digital_codes_count AS digital_codes_count,
    financial_product_id,
    financial_payout,
    financial_old_price,
    financial_price,
    financial_total_discount_value,
    financial_total_discount_percent,
    financial_actions_count,
    financial_commission_amount,
    financial_commission_percent,
    financial_commission_currency,
    source_run_id,
    updated_at
FROM staging.ozon_fbo_order_items_full;

DROP TABLE IF EXISTS staging.ozon_order_items;
DROP TABLE IF EXISTS staging.ozon_order_item_details;
DROP TABLE IF EXISTS staging.ozon_fbo_posting_details;
